#!/usr/bin/env python3
"""
Achaea processed dataset -> Mudlet Lua exporter.

Reads indexes produced by achaea_post_processor_fixed.py and generates
Mudlet-ready Lua tables for commands, abilities, afflictions, defences,
classes, skills, relations, and retrieval metadata.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any


def load_json(path: Path, default: Any):
    if not path.exists():
        return default
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def lua_escape_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
        .replace('"', '\\"')
    )


def to_lua(value: Any, indent: int = 0) -> str:
    pad = " " * indent
    next_pad = " " * (indent + 2)

    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return f'"{lua_escape_string(value)}"'
    if isinstance(value, list):
        if not value:
            return "{}"
        items = [f"{next_pad}{to_lua(item, indent + 2)}" for item in value]
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = []
        for key in sorted(value.keys(), key=lambda k: str(k)):
            if isinstance(key, str) and key.isidentifier():
                lua_key = key
            else:
                lua_key = f"[{to_lua(str(key))}]"
            items.append(f"{next_pad}{lua_key} = {to_lua(value[key], indent + 2)}")
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    return f'"{lua_escape_string(str(value))}"'


def write_lua_module(path: Path, module_name: str, table_name: str, data: Any, header: str | None = None) -> None:
    lines = ["-- Auto-generated by achaea_lua_exporter.py"]
    if header:
        lines.append(f"-- {header}")
    lines.extend(
        [
            f"local {table_name} = {to_lua(data)}",
            "",
            f"return {table_name}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def build_manifest(indexes: dict[str, Any]) -> dict[str, Any]:
    return {
        "generated_from": "processed/indexes",
        "counts": {
            name: (len(value) if isinstance(value, (list, dict)) else 0)
            for name, value in indexes.items()
        },
        "modules": {
            "command_index": "silverfury_data/command_index.lua",
            "ability_index": "silverfury_data/ability_index.lua",
            "affliction_index": "silverfury_data/affliction_index.lua",
            "defence_index": "silverfury_data/defence_index.lua",
            "class_index": "silverfury_data/class_index.lua",
            "skill_index": "silverfury_data/skill_index.lua",
            "relations": "silverfury_data/relations.lua",
            "command_names": "silverfury_data/command_names.lua",
        },
    }


def build_bootstrap_module(module_files: list[str]) -> str:
    require_lines = []
    export_lines = []
    for filename in module_files:
        stem = Path(filename).stem
        require_lines.append(f'local {stem} = require("silverfury_data.{stem}")')
        export_lines.append(f"  {stem} = {stem},")
    return "\n".join(
        [
            "-- Auto-generated by achaea_lua_exporter.py",
            *require_lines,
            "",
            "local M = {",
            *export_lines,
            "}",
            "",
            "return M",
            "",
        ]
    )


def export_dataset(dataset_dir: Path, output_dir: Path) -> tuple[int, Path]:
    indexes_dir = dataset_dir / "processed" / "indexes"
    if not indexes_dir.exists():
        raise FileNotFoundError(
            f"Could not find processed indexes at: {indexes_dir}. Run the fixed post-processor first."
        )

    ensure_dir(output_dir)

    index_files = {
        "command_index": indexes_dir / "command_index.json",
        "ability_index": indexes_dir / "ability_index.json",
        "affliction_index": indexes_dir / "affliction_index.json",
        "defence_index": indexes_dir / "defence_index.json",
        "class_index": indexes_dir / "class_index.json",
        "skill_index": indexes_dir / "skill_index.json",
        "relations": indexes_dir / "relations.json",
        "command_names": indexes_dir / "command_names.json",
    }

    loaded: dict[str, Any] = {}
    for key, path in index_files.items():
        loaded[key] = load_json(path, {} if key != "command_names" else [])

    lua_module_files = []
    for key, data in loaded.items():
        lua_name = f"{key}.lua"
        lua_path = output_dir / lua_name
        write_lua_module(lua_path, key, key, data, header=f"Source: {index_files[key].name}")
        lua_module_files.append(lua_name)

    manifest = build_manifest(loaded)
    write_lua_module(output_dir / "manifest.lua", "manifest", "manifest", manifest, header="Exporter manifest")
    lua_module_files.append("manifest.lua")

    (output_dir / "init.lua").write_text(build_bootstrap_module(lua_module_files), encoding="utf-8")

    helper = """-- Auto-generated helper lookup functions for Silverfury/Mudlet
local data = require(\"silverfury_data.init\")

local M = {}

local function normalize(value)
  if type(value) ~= \"string\" then return value end
  return value:lower():gsub(\"^%s+\", \"\"):gsub(\"%s+$\", \"\")
end

function M.get_command(name)
  if not name then return nil end
  local key = normalize(name)
  return data.command_index[key] or data.command_index[name]
end

function M.get_ability(name)
  if not name then return nil end
  local key = normalize(name)
  return data.ability_index[key] or data.ability_index[name]
end

function M.has_affliction(name)
  if not name then return false end
  local key = normalize(name)
  return data.affliction_index[key] ~= nil or data.affliction_index[name] ~= nil
end

function M.has_defence(name)
  if not name then return false end
  local key = normalize(name)
  return data.defence_index[key] ~= nil or data.defence_index[name] ~= nil
end

function M.get_skill(name)
  if not name then return nil end
  local key = normalize(name)
  return data.skill_index[key] or data.skill_index[name]
end

return M
"""
    (output_dir / "lookup.lua").write_text(helper, encoding="utf-8")

    return len(lua_module_files) + 2, output_dir


def main() -> None:
    parser = argparse.ArgumentParser(description="Export processed Achaea dataset indexes into Mudlet-ready Lua tables.")
    parser.add_argument("--dataset-dir", default="achaea_help_dataset", help="Path to the spider dataset folder.")
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Output folder for Lua files. Default: <dataset-dir>/processed/lua/silverfury_data",
    )
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir).resolve()
    output_dir = Path(args.output_dir).resolve() if args.output_dir else dataset_dir / "processed" / "lua" / "silverfury_data"

    count, path = export_dataset(dataset_dir, output_dir)
    print(f"Exported {count} Lua files to {path}")
    print("Mudlet entrypoint: silverfury_data/init.lua")
    print("Lookup helpers: silverfury_data/lookup.lua")


if __name__ == "__main__":
    main()
